name: build and push container image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      application:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      password: {}

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up qemu
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: check dockerfile policy
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: dockerfile
          dockerfile_path: .
          check: CKV_DOCKER_7,CKV_DOCKER_8,CKV_DOCKER_10

      - name: push container image to container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.application }}:${{ inputs.version }}
