name: Build pipeline

on:
  pull_request:
    branches:
      - dev

env:
  REGISTRY: ghcr.io/${{ github.actor }}/
  APPLICATION: sample-app
  VERSION: latest

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: login to github packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set short commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build temporary container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.actor }}/sample-app:${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
      - name: push container image to container registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/sample-app:${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}
