name: sca scan poetry

on:
  workflow_call:
    secrets:
      snyk_token: {}

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: install dependencies
        run: poetry install --no-interaction --no-root --with dev

      - name: snyk scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
